services:
  train_and_run:
    build:
      context: .
      dockerfile: docker/Dockerfile.cicd
      args:
        MODEL_NAME: ${MODEL_NAME}
        MODEL_VERSION: ${MODEL_VERSION}
        RANDOM_SEED: ${RANDOM_SEED}
        TEST_SIZE: ${TEST_SIZE}
        MODEL_TYPE: ${MODEL_TYPE}
    container_name: mlops-python-auto-train
    env_file:
      - .env
    ports:
      - "9696:9696"
